name: thj_first_flutter
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=2.3.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  shared_preferences: ^0.4.3
  event_bus: ^1.0.1
  fluttertoast: ^3.0.4
  flutter_swiper: ^1.1.6
  transformer_page_view: ^0.1.6
  flutter_page_indicator: ^0.0.3
  dio: ^3.0.9
  toast: ^0.1.3
  encrypt: ^2.2.0
  password: ^1.0.0
  password_hash: ^2.0.0
  json_annotation: ^2.2.0
  flutter_easyrefresh: ^1.2.7
  webview_flutter: ^0.3.9+1
  flutter_spinkit: ^3.1.0
  flutter_bloc: ^0.13.0
  rxdart: ^0.22.0
  scoped_model: ^1.0.1
  pull_to_refresh: ^1.3.5
  loading: ^1.0.0
  provider: ^4.1.3
  fluwx: ^0.6.3
  flutter_bugly: ^0.2.2
  jpush_flutter: ^0.0.11
  fluro: ^1.7.8
  common_utils: ^1.1.1
  image_picker: ^0.6.0+10
#  mobpush: ^0.0.5
  fish_redux: ^0.3.4
  flutter_redux: ^0.6.0
  redux: ^4.0.0
  r_dart_library:
    git:
      url: https://github.com/YK-Unit/r_dart_library.git
      ref: 0.2.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.3.3
  json_serializable: ^2.2.1
flutter:
  uses-material-design: true
  fonts:
    - family: appIconFonts
      fonts:
        - asset: assets/fonts/iconfont.ttf
  assets:
  - images/
  - images/discover/
  - images/home/
  - images/me/
  - images/tabbar/


flr:
  core_version: 3.0.0
  dartfmt_line_length: 80
  assets:
  - images
